name: 'Set up for "nx affected" commands'
description: Checks out source code then calculates head and base SHAs for running "nx affected" commands on "pull_request" events.

runs:
  using: composite

  steps:
    - name: Check out source code
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ (github.event_name == 'push' && github.base_ref == 'refs/heads/main') && 1 || 0 }}
        ref: ${{ github.event_name == 'pull_request' && github.pull_request.head.ref || '' }}
    - name: 'PR: Derive appropriate SHAs for base and head for `nx affected` commands'
      if: github.event_name == 'pull_request'
      uses: nrwl/nx-set-shas@v2
