name: Energy Insights CI

env:
  node-version: 14.x
  NODE_OPTIONS: --max_old_space_size=6144
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
  workflow_dispatch:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - name: Install PNPM
        run: npm install --global pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --verify-store-integrity false

      - name: Build Angular app
        run: pnpm build
  lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - name: Install PNPM
        run: npm install --global pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --verify-store-integrity false

      - name: Lint workspace and projects
        run: pnpm lint
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - name: Install PNPM
        run: npm install --global pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --verify-store-integrity false

      - name: Test projects
        run: pnpm test
