name: CI

env:
  is-main-branch: ${{ github.event_name == 'push' && github.base_ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
  is-feature-branch: ${{ github.event_name == 'pull_request' && github.head_ref != 'main' || github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main' }}
  NODE_OPTIONS: --max-old-space-size=6144
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

# concurrency:
#   # Group concurrency on workflow, then:
#   # - Is main branch run? Group `push` and `workflow_dispatch` events
#   # - Is feature branch run? Group `pull_request` and `workflow_dispatch` events
#   group: ${{ github.workflow }}-${{ ((github.event_name == 'push' && github.base_ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') && github.base_ref || github.ref) || github.head_ref || github.ref }}
#   # Run main branch runs in sequence. Cancel in progress feature branch runs.
#   cancel-in-progress: ${{ (github.event_name == 'push' && github.base_ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') && 'false' || 'true' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: 'PR: Build application if affected by changes in feature branch'
        if: env.is-feature-branch == 'true'
        run: yarn build
      - name: 'Merge: Build application'
        if: env.is-main-branch == 'true'
        run: yarn build

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: 'PR: Lint workspace and affected projects'
        if: env.is-feature-branch == 'true'
        run: yarn affected:lint
      - name: 'Merge: Lint workspace and all projects'
        if: env.is-main-branch == 'true'
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: 'PR: Test affected projects'
        if: env.is-feature-branch == 'true'
        run: yarn test
      - name: 'Merge: Test all projects'
        if: env.is-main-branch == 'true'
        run: yarn test

  e2e:
    name: End-to-end test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: 'PR: End-to-end test application if affected by changes in feature branch'
        if: env.is-feature-branch == 'true'
        run: yarn affected:e2e
      - name: 'Merge: End-to-end test application'
        if: env.is-main-branch == 'true'
        run: yarn e2e
