name: CI

env:
  NODE_OPTIONS: --max-old-space-size=6144
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Build Angular app
        run: yarn build
  lint:
    name: 'PR: Lint'
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Lint workspace and projects
        run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Test projects
        run: yarn test
  e2e:
    name: End-to-end test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: End-to-end test application
        run: yarn e2e
