name: CI

env:
  # Branching
  is-merge: ${{ github.event_name == 'push' }}
  is-pull-request: ${{ github.event_name == 'pull_request' }}

  # Check out
  checkout-fetch-depth: ${{ github.event_name == 'push' && 1 || 0 }}
  checkout-ref: ${{ github.event_name == 'pull_request' && github.pull_request.head.ref || '' }}

  # Node.js
  NODE_OPTIONS: --max-old-space-size=6144

on:
  push:
    branches:
      - main
  pull_request: {}

# Test cancel

concurrency:
  # Group concurrency on workflow, then:
  # - Is merge run? Group `push` events
  # - Is pull request? Group `pull_request` events
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.base_ref || github.head_ref }}
  # Run merge runs in sequence. Cancel in progress pull request runs.
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.checkout-fetch-depth }}
          ref: ${{ env.checkout-ref }}
      - name: 'PR: Derive appropriate SHAs for base and head for `nx affected` commands'
        if: github.event_name == 'pull_request'
        uses: nrwl/nx-set-shas@v2
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: 'PR: Build application if affected by changes in feature branch'
        if: env.is-pull-request == 'true'
        run: yarn build
      - name: 'Merge: Build application'
        if: env.is-merge == 'true'
        run: yarn build

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.checkout-fetch-depth }}
          ref: ${{ env.checkout-ref }}
      - name: 'PR: Derive appropriate SHAs for base and head for `nx affected` commands'
        if: github.event_name == 'pull_request'
        uses: nrwl/nx-set-shas@v2
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: 'PR: Lint workspace and affected projects'
        if: env.is-pull-request == 'true'
        run: yarn affected:lint
      - name: 'Merge: Lint workspace and all projects'
        if: env.is-merge == 'true'
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.checkout-fetch-depth }}
          ref: ${{ env.checkout-ref }}
      - name: 'PR: Derive appropriate SHAs for base and head for `nx affected` commands'
        if: github.event_name == 'pull_request'
        uses: nrwl/nx-set-shas@v2
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: 'PR: Test affected projects'
        if: env.is-pull-request == 'true'
        run: yarn test
      - name: 'Merge: Test all projects'
        if: env.is-merge == 'true'
        run: yarn test

  e2e:
    name: End-to-end test
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.checkout-fetch-depth }}
          ref: ${{ env.checkout-ref }}
      - name: 'PR: Derive appropriate SHAs for base and head for `nx affected` commands'
        if: github.event_name == 'pull_request'
        uses: nrwl/nx-set-shas@v2
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: 'PR: End-to-end test application if affected by changes in feature branch'
        if: env.is-pull-request == 'true'
        run: yarn affected:e2e
      - name: 'Merge: End-to-end test application'
        if: env.is-merge == 'true'
        run: yarn e2e
